language: node_js
node_js:
  - "10"
  - "9"

before_script:
  - npm install -g pkg
  -
script:
  - npm run build
  - ls

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "preview-win.exe"
  skip_cleanup: true
  overwrite: true
  on:
    tags: false
